name: Demo FLow
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      REACT_APP_IS_PRODUCTION: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: yarn

      - run: echo "${{ github.ref }}"
      # - name: Set appropriate env variable
      #   run: echo "REACT_APP_NODE_ENV=production" >> $GITHUB_ENV
      #   if: startsWith(github.event_name , 'refs/heads/prod')

      # - name: Run tests
      #   run: yarn test

      # - name: Build artifact
      #   run: yarn build
