name: Demo Manual FLow
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      REACT_APP_NODE_ENV: ${{ secrets.REACT_APP_STAGING_NODE_ENV }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build artifact
        run: yarn build
